from pathlib import Path
import os

# Перечень переменных окружения, которые очищаются при запуске
# перед запуском сервиса — для избежания нежелательных конфликтов.
ENV_VARS_TO_CLEAR = [
    "DEBUG",
    "APP_ROLE",
    "BOT_TOKEN",
    "BOT_ADMINS",
    "BOT_SUPERUSERS",
    "BOT_ROLE_ACCESS",
    "BOT_RATE_LIMIT",
    "DB_ENGINE",
    "DB_ECHO",
    "SQLITE_FILE",
    "POSTGRES_HOST",
    "POSTGRES_PORT",
    "POSTGRES_USER",
    "POSTGRES_PASSWORD",
    "POSTGRES_DB",
    "MYSQL_HOST",
    "MYSQL_PORT",
    "MYSQL_USER",
    "MYSQL_PASSWORD",
    "MYSQL_DB",
    "USE_REDIS",
    "REDIS_HOST",
    "REDIS_PORT",
    "REDIS_PASSWORD",
    "REDIS_DB",
    "USE_MONGODB",
    "MONGO_URI",
    "MONGO_DB_NAME",
    "MONGO_PORT",
    "MONGO_USER",
    "MONGO_PASSWORD",
    "SECURITY_ACCESS_TOKEN_EXPIRE_MINUTES",
    "SECURITY_JWT_SECRET",
    "SECURITY_ADMIN_PASSWORD",
    "JWT_ALGORITHM",
    "SECURITY_USE_SPECIAL_CHAR",
    "SECURITY_MIN_LENGTH",
    "EMAIL_SMTP_HOST",
    "EMAIL_SMTP_PORT",
    "EMAIL_SMTP_USER",
    "EMAIL_SMTP_PASSWORD",
    "EMAIL_FROM",
    "EMAIL_ENABLE_TLS",
    "EMAIL_SUPPORT_EMAIL",
    "EMAIL_ADMIN_EMAIL",
    "API_HOST",
    "API_PORT",
    "API_WORKERS",
    "NETWORK_PING_COUNT",
    "NETWORK_PING_INTERVAL",
    "NETWORK_PING_TIMEOUT",
    "NETWORK_SNMP_RO",
    "NETWORK_SNMP_RW",
    "USE_CACHE",
    "CACHE_TYPE",
    "CACHE_REDIS_HOST",
    "CACHE_REDIS_PORT",
    "CACHE_REDIS_DB",
    "CACHE_REDIS_PASSWORD",
    "TFA_ENABLE",
    "TFA_MANDATORY",
    "TIMEZONE",
    "MAX_PAYLOAD_SIZE_MB",
    "EXCLUDED_SUBSTRINGS",
]

# Пути, где ищется файл с конфигурацией среды по умолчанию,
# проверяются в указанном порядке:
# 1) напрямую из переменной TGNMS_ENV_FILE,
# 2) в текущем каталоге проекта,
# 3) в домашней директории пользователя,
# 4) в системном каталоге /etc/tgnms/.
DEFAULT_CONFIG_PATHS = [
    Path(os.getenv("TGNMS_ENV_FILE", "")),
    Path.cwd() / ".tgnmsrc",
    Path.home() / ".tgnmsrc",
    Path("/etc/tgnms/.tgnmsrc"),
]
